package yazlab1.proje2;

import javax.swing.JLabel;

public class OutputFrame extends javax.swing.JFrame {

    /**
     * Creates new form OutputFrame
     */
    public OutputFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        floor0 = new javax.swing.JLabel();
        floor1 = new javax.swing.JLabel();
        floor2 = new javax.swing.JLabel();
        floor3 = new javax.swing.JLabel();
        floor4 = new javax.swing.JLabel();
        exit_count = new javax.swing.JLabel();
        active1 = new javax.swing.JLabel();
        mode1 = new javax.swing.JLabel();
        floorText1 = new javax.swing.JLabel();
        elevator1Label = new javax.swing.JLabel();
        destination1 = new javax.swing.JLabel();
        direction1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        countinside1 = new javax.swing.JLabel();
        inside1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        active2 = new javax.swing.JLabel();
        mode2 = new javax.swing.JLabel();
        floorText2 = new javax.swing.JLabel();
        destination2 = new javax.swing.JLabel();
        direction2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        countinside2 = new javax.swing.JLabel();
        inside2 = new javax.swing.JLabel();
        elevator2Label = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        active3 = new javax.swing.JLabel();
        mode3 = new javax.swing.JLabel();
        floorText3 = new javax.swing.JLabel();
        destination3 = new javax.swing.JLabel();
        direction3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        countinside3 = new javax.swing.JLabel();
        inside3 = new javax.swing.JLabel();
        elevator3Label = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        active4 = new javax.swing.JLabel();
        mode4 = new javax.swing.JLabel();
        floorText4 = new javax.swing.JLabel();
        destination4 = new javax.swing.JLabel();
        direction4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        countinside4 = new javax.swing.JLabel();
        inside4 = new javax.swing.JLabel();
        elevator4Label = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        active5 = new javax.swing.JLabel();
        mode5 = new javax.swing.JLabel();
        floorText5 = new javax.swing.JLabel();
        destination5 = new javax.swing.JLabel();
        direction5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        countinside5 = new javax.swing.JLabel();
        inside5 = new javax.swing.JLabel();
        elevator5Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        floor0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floor0.setForeground(new java.awt.Color(255, 255, 255));
        floor0.setText("jLabel0");

        floor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floor1.setForeground(new java.awt.Color(255, 255, 255));
        floor1.setText("jLabel1");

        floor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floor2.setForeground(new java.awt.Color(255, 255, 255));
        floor2.setText("jLabel2");

        floor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floor3.setForeground(new java.awt.Color(255, 255, 255));
        floor3.setText("jLabel3");

        floor4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floor4.setForeground(new java.awt.Color(255, 255, 255));
        floor4.setText("jLabel4");

        exit_count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit_count.setForeground(new java.awt.Color(255, 255, 255));
        exit_count.setText("exit_count");

        active1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        active1.setForeground(new java.awt.Color(255, 255, 255));
        active1.setText("active: True");

        mode1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mode1.setForeground(new java.awt.Color(255, 255, 255));

        floorText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorText1.setForeground(new java.awt.Color(255, 255, 255));

        elevator1Label.setBackground(new java.awt.Color(255, 255, 255));
        elevator1Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elevator1Label.setForeground(new java.awt.Color(255, 255, 255));
        elevator1Label.setText("Asansör-1");

        destination1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination1.setForeground(new java.awt.Color(255, 255, 255));
        destination1.setText("destination1");

        direction1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direction1.setForeground(new java.awt.Color(255, 255, 255));
        direction1.setText("direction1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("capacity: 10");

        countinside1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countinside1.setForeground(new java.awt.Color(255, 255, 255));
        countinside1.setText("count_inside1");

        inside1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inside1.setForeground(new java.awt.Color(255, 255, 255));
        inside1.setText("inside1");

        active2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        active2.setForeground(new java.awt.Color(255, 255, 255));
        active2.setText("active2");

        mode2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mode2.setForeground(new java.awt.Color(255, 255, 255));
        mode2.setText("mode2");

        floorText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorText2.setForeground(new java.awt.Color(255, 255, 255));
        floorText2.setText("floor2");

        destination2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination2.setForeground(new java.awt.Color(255, 255, 255));
        destination2.setText("destination2");

        direction2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direction2.setForeground(new java.awt.Color(255, 255, 255));
        direction2.setText("direction2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("capacity: 10");

        countinside2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countinside2.setForeground(new java.awt.Color(255, 255, 255));
        countinside2.setText("count_inside2");

        inside2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inside2.setForeground(new java.awt.Color(255, 255, 255));
        inside2.setText("inside2");

        elevator2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elevator2Label.setForeground(new java.awt.Color(255, 255, 255));
        elevator2Label.setText("Asansör-2");

        active3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        active3.setForeground(new java.awt.Color(255, 255, 255));
        active3.setText("active3");

        mode3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mode3.setForeground(new java.awt.Color(255, 255, 255));
        mode3.setText("mode3");

        floorText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorText3.setForeground(new java.awt.Color(255, 255, 255));
        floorText3.setText("floor3");

        destination3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination3.setForeground(new java.awt.Color(255, 255, 255));
        destination3.setText("destination3");

        direction3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direction3.setForeground(new java.awt.Color(255, 255, 255));
        direction3.setText("direction3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("capacity: 10");

        countinside3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countinside3.setForeground(new java.awt.Color(255, 255, 255));
        countinside3.setText("count_inside3");

        inside3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inside3.setForeground(new java.awt.Color(255, 255, 255));
        inside3.setText("inside3");

        elevator3Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elevator3Label.setForeground(new java.awt.Color(255, 255, 255));
        elevator3Label.setText("Asansör-3");

        active4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        active4.setForeground(new java.awt.Color(255, 255, 255));
        active4.setText("active4");

        mode4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mode4.setForeground(new java.awt.Color(255, 255, 255));
        mode4.setText("mode4");

        floorText4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorText4.setForeground(new java.awt.Color(255, 255, 255));
        floorText4.setText("floorText4");

        destination4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination4.setForeground(new java.awt.Color(255, 255, 255));
        destination4.setText("destination4");

        direction4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direction4.setForeground(new java.awt.Color(255, 255, 255));
        direction4.setText("direction4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("capacity: 10");

        countinside4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countinside4.setForeground(new java.awt.Color(255, 255, 255));
        countinside4.setText("count_inside4");

        inside4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inside4.setForeground(new java.awt.Color(255, 255, 255));
        inside4.setText("inside4");

        elevator4Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elevator4Label.setForeground(new java.awt.Color(255, 255, 255));
        elevator4Label.setText("Asansör-4");

        active5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        active5.setForeground(new java.awt.Color(255, 255, 255));
        active5.setText("active5");

        mode5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mode5.setForeground(new java.awt.Color(255, 255, 255));
        mode5.setText("mode5");

        floorText5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorText5.setForeground(new java.awt.Color(255, 255, 255));
        floorText5.setText("floor5");

        destination5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination5.setForeground(new java.awt.Color(255, 255, 255));
        destination5.setText("destination5");

        direction5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direction5.setForeground(new java.awt.Color(255, 255, 255));
        direction5.setText("direction5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("capacity: 10");

        countinside5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countinside5.setForeground(new java.awt.Color(255, 255, 255));
        countinside5.setText("count_inside5");

        inside5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inside5.setForeground(new java.awt.Color(255, 255, 255));
        inside5.setText("inside5");

        elevator5Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elevator5Label.setForeground(new java.awt.Color(255, 255, 255));
        elevator5Label.setText("Asansör-5");

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mode1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floorText1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destination1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direction1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countinside1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inside1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(elevator1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floor0, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exit_count, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(floor3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(active1, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(active2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(mode2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(floorText2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(destination2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(direction2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(elevator2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(countinside2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(inside2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(active3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(mode3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(floorText3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(destination3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(elevator3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(direction3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(countinside3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(inside3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(active4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(active5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(mode4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377)
                .addComponent(mode5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floorText4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direction4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(elevator4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floorText5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direction5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countinside5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(elevator5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(countinside4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377)
                .addComponent(inside5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(inside4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(elevator1Label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(floor0)
                        .addGap(3, 3, 3)
                        .addComponent(floor1)
                        .addGap(43, 43, 43)
                        .addComponent(floor4)
                        .addGap(3, 3, 3)
                        .addComponent(exit_count))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(floor2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(floor3))
                    .addComponent(active1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mode1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floorText1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destination1)
                                .addGap(6, 6, 6)
                                .addComponent(direction1)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(countinside1)))
                        .addGap(6, 6, 6)
                        .addComponent(inside1)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(active2)
                .addGap(6, 6, 6)
                .addComponent(mode2)
                .addGap(6, 6, 6)
                .addComponent(floorText2)
                .addGap(6, 6, 6)
                .addComponent(destination2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direction2)
                    .addComponent(elevator2Label))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(countinside2)
                .addGap(6, 6, 6)
                .addComponent(inside2)
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(active3)
                .addGap(6, 6, 6)
                .addComponent(mode3)
                .addGap(6, 6, 6)
                .addComponent(floorText3)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destination3)
                    .addComponent(elevator3Label))
                .addGap(6, 6, 6)
                .addComponent(direction3)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(countinside3)
                .addGap(6, 6, 6)
                .addComponent(inside3)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(active4)
                    .addComponent(active5))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mode4)
                    .addComponent(mode5))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(floorText4)
                        .addGap(6, 6, 6)
                        .addComponent(destination4)
                        .addGap(6, 6, 6)
                        .addComponent(direction4)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(elevator4Label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(floorText5)
                        .addGap(3, 3, 3)
                        .addComponent(destination5)
                        .addGap(3, 3, 3)
                        .addComponent(direction5)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(countinside5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(elevator5Label)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countinside4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(inside5)))
                .addGap(3, 3, 3)
                .addComponent(inside4))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 1190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JLabel[] labels = new JLabel[42];
        labels[0] = floor0;
        labels[1] = floor1;
        labels[2] = floor2;
        labels[3] = floor3;
        labels[4] = floor4;
        labels[5] = exit_count;
        labels[6] = active1;
        labels[7] = active2;
        labels[8] = active3;
        labels[9] = active4;
        labels[10] = active5;
        labels[11] = mode1;
        labels[12] = mode2;
        labels[13] = mode3;
        labels[14] = mode4;
        labels[15] = mode5;
        labels[16] = floorText1;
        labels[17] = floorText2;
        labels[18] = floorText3;
        labels[19] = floorText4;
        labels[20] = floorText5;
        labels[21] = destination1;
        labels[22] = destination2;
        labels[23] = destination3;
        labels[24] = destination4;
        labels[25] = destination5;
        labels[26] = direction1;
        labels[27] = direction2;
        labels[28] = direction3;
        labels[29] = direction4;
        labels[30] = direction5;
        labels[31] = countinside1;
        labels[32] = countinside2;
        labels[33] = countinside3;
        labels[34] = countinside4;
        labels[35] = countinside5;
        labels[36] = inside1;
        labels[37] = inside2;
        labels[38] = inside3;
        labels[39] = inside4;
        labels[40] = inside5;
        labels[41] = jLabel1;
        Main m = new Main();

        elevator1 elev1 = new elevator1(labels);
        elevator2 elev2 = new elevator2(labels);
        elevator3 elev3 = new elevator3(labels);
        elevator4 elev4 = new elevator4(labels);
        elevator5 elev5 = new elevator5(labels);


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel active1;
    private javax.swing.JLabel active2;
    private javax.swing.JLabel active3;
    private javax.swing.JLabel active4;
    private javax.swing.JLabel active5;
    private javax.swing.JLabel countinside1;
    private javax.swing.JLabel countinside2;
    private javax.swing.JLabel countinside3;
    private javax.swing.JLabel countinside4;
    private javax.swing.JLabel countinside5;
    private javax.swing.JLabel destination1;
    private javax.swing.JLabel destination2;
    private javax.swing.JLabel destination3;
    private javax.swing.JLabel destination4;
    private javax.swing.JLabel destination5;
    private javax.swing.JLabel direction1;
    private javax.swing.JLabel direction2;
    private javax.swing.JLabel direction3;
    private javax.swing.JLabel direction4;
    private javax.swing.JLabel direction5;
    private javax.swing.JLabel elevator1Label;
    private javax.swing.JLabel elevator2Label;
    private javax.swing.JLabel elevator3Label;
    private javax.swing.JLabel elevator4Label;
    private javax.swing.JLabel elevator5Label;
    private javax.swing.JLabel exit_count;
    private javax.swing.JLabel floor0;
    private javax.swing.JLabel floor1;
    private javax.swing.JLabel floor2;
    private javax.swing.JLabel floor3;
    private javax.swing.JLabel floor4;
    private javax.swing.JLabel floorText1;
    private javax.swing.JLabel floorText2;
    private javax.swing.JLabel floorText3;
    private javax.swing.JLabel floorText4;
    private javax.swing.JLabel floorText5;
    private javax.swing.JLabel inside1;
    private javax.swing.JLabel inside2;
    private javax.swing.JLabel inside3;
    private javax.swing.JLabel inside4;
    private javax.swing.JLabel inside5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel mode1;
    private javax.swing.JLabel mode2;
    private javax.swing.JLabel mode3;
    private javax.swing.JLabel mode4;
    private javax.swing.JLabel mode5;
    // End of variables declaration//GEN-END:variables
}
